// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MQEC_Api.Models
{
    public partial class AllowanceFormNo
    {
        [Key]
        [Column("Company_No")]
        [StringLength(10)]
        public string CompanyNo { get; set; }
        [Key]
        [StringLength(20)]
        public string FormNo { get; set; }
    }
}