// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MQEC_Api.Models
{
    public partial class AllowanceDetails
    {
        [Key]
        [Column("Company_No")]
        [StringLength(50)]
        public string CompanyNo { get; set; }
        [Key]
        [Column("Allowance_No")]
        [StringLength(20)]
        public string AllowanceNo { get; set; }
        [Key]
        public int Serno { get; set; }
        [Required]
        [StringLength(50)]
        public string Prodid { get; set; }
        [Required]
        [StringLength(256)]
        public string Description { get; set; }
        [Required]
        [StringLength(6)]
        public string Unit { get; set; }
        [Required]
        [Column("TaxType_No")]
        [StringLength(10)]
        public string TaxTypeNo { get; set; }
        [Required]
        [Column("CurrencyID")]
        [StringLength(3)]
        public string CurrencyId { get; set; }
        [Column("Exchange_Rate", TypeName = "decimal(12, 2)")]
        public decimal ExchangeRate { get; set; }
        [Column("Allowance_Qty")]
        public int AllowanceQty { get; set; }
        [Column("Allowance_Price", TypeName = "decimal(12, 2)")]
        public decimal AllowancePrice { get; set; }
        [Column("Allowance_Amount", TypeName = "decimal(12, 2)")]
        public decimal AllowanceAmount { get; set; }
        [Column("Tax_Amount", TypeName = "decimal(12, 2)")]
        public decimal TaxAmount { get; set; }
        [Column("Gross_Amount", TypeName = "decimal(12, 2)")]
        public decimal GrossAmount { get; set; }
        [Required]
        [StringLength(10)]
        public string InvoiceNumber { get; set; }
        [Required]
        [StringLength(10)]
        public string InvoiceDate { get; set; }
        public int InvoiceSerno { get; set; }
        [Required]
        [Column("Co1_D_1")]
        [StringLength(255)]
        public string? Co1D1 { get; set; }
        [Required]
        [Column("Co1_D_2")]
        [StringLength(255)]
        public string? Co1D2 { get; set; }
        [Required]
        [Column("Co1_D_3")]
        [StringLength(255)]
        public string? Co1D3 { get; set; }
        [Required]
        [Column("Co1_D_4")]
        [StringLength(255)]
        public string? Co1D4 { get; set; }
        [Required]
        [Column("Co1_D_5")]
        [StringLength(255)]
        public string? Co1D5 { get; set; }
        [Required]
        [Column("Co1_D_6")]
        [StringLength(255)]
        public string? Co1D6 { get; set; }
        [Required]
        [Column("Co1_D_7")]
        [StringLength(255)]
        public string? Co1D7 { get; set; }
        [Required]
        [Column("Co1_D_8")]
        [StringLength(255)]
        public string? Co1D8 { get; set; }
        [Required]
        [Column("Co1_D_9")]
        [StringLength(255)]
        public string? Co1D9 { get; set; }
        [Required]
        [Column("Co1_D_10")]
        [StringLength(255)]
        public string? Co1D10 { get; set; }
    }
}