// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MQEC_Api.Models
{
    public partial class Allowance
    {
        [Key]
        [Column("Company_No")]
        [StringLength(50)]
        public string CompanyNo { get; set; }
        [Key]
        [Column("Allowance_No")]
        [StringLength(20)]
        public string AllowanceNo { get; set; }
        [Required]
        [Column("OriAllowance_No")]
        [StringLength(50)]
        public string OriAllowanceNo { get; set; }
        [Required]
        [Column("Allowance_Type")]
        [StringLength(10)]
        public string AllowanceType { get; set; }
        [Column("Allowance_Date", TypeName = "date")]
        public DateTime? AllowanceDate { get; set; }
        [Required]
        [StringLength(5)]
        public string InvoiceCategory { get; set; }
        [Required]
        public string Memo { get; set; }
        [Required]
        [Column("Seller_ID")]
        [StringLength(10)]
        public string SellerId { get; set; }
        [Required]
        [Column("Seller_Name")]
        [StringLength(60)]
        public string SellerName { get; set; }
        [Required]
        [Column("Seller_Address")]
        [StringLength(100)]
        public string SellerAddress { get; set; }
        [Required]
        [Column("Seller_PersonInCharge")]
        [StringLength(30)]
        public string SellerPersonInCharge { get; set; }
        [Required]
        [Column("Seller_TelephoneNumber")]
        [StringLength(25)]
        public string SellerTelephoneNumber { get; set; }
        [Required]
        [Column("Seller_FacsimileNumber")]
        [StringLength(25)]
        public string SellerFacsimileNumber { get; set; }
        [Required]
        [Column("Seller_EmailAddress")]
        [StringLength(80)]
        public string SellerEmailAddress { get; set; }
        [Required]
        [Column("Seller_CustomerNumber")]
        [StringLength(20)]
        public string SellerCustomerNumber { get; set; }
        [Required]
        [Column("Seller_RoleRemark")]
        [StringLength(40)]
        public string SellerRoleRemark { get; set; }
        [Required]
        [Column("Buyer_ID")]
        [StringLength(10)]
        public string BuyerId { get; set; }
        [Required]
        [Column("Buyer_Name")]
        [StringLength(60)]
        public string BuyerName { get; set; }
        [Required]
        [Column("Buyer_Address")]
        [StringLength(100)]
        public string BuyerAddress { get; set; }
        [Required]
        [Column("Buyer_PersonInCharge")]
        [StringLength(30)]
        public string BuyerPersonInCharge { get; set; }
        [Required]
        [Column("Buyer_TelephoneNumber")]
        [StringLength(25)]
        public string BuyerTelephoneNumber { get; set; }
        [Required]
        [Column("Buyer_FacsimileNumber")]
        [StringLength(25)]
        public string BuyerFacsimileNumber { get; set; }
        [Required]
        [Column("Buyer_EmailAddress")]
        [StringLength(80)]
        public string BuyerEmailAddress { get; set; }
        [Required]
        [Column("Buyer_CustomerNumber")]
        [StringLength(20)]
        public string BuyerCustomerNumber { get; set; }
        [Required]
        [Column("Buyer_RoleRemark")]
        [StringLength(40)]
        public string BuyerRoleRemark { get; set; }
        [Column("Net_Allowance", TypeName = "decimal(12, 2)")]
        public decimal NetAllowance { get; set; }
        [Column("Allowance_Tax", TypeName = "decimal(12, 2)")]
        public decimal AllowanceTax { get; set; }
        [Column("Allowance_Amount", TypeName = "decimal(12, 2)")]
        public decimal AllowanceAmount { get; set; }
        [Column(TypeName = "decimal(12, 2)")]
        public decimal TaxRate { get; set; }
        [Required]
        [Column("CurrencyID")]
        [StringLength(3)]
        public string CurrencyId { get; set; }
        [Column("Exchange_Rate", TypeName = "decimal(12, 2)")]
        public decimal ExchangeRate { get; set; }
        [Column("Open_Summons")]
        public bool OpenSummons { get; set; }
        [Column("Create_Date", TypeName = "datetime")]
        public DateTime CreateDate { get; set; }
        [Required]
        [Column("Create_User")]
        [StringLength(50)]
        public string CreateUser { get; set; }
        [Column("Update_Date", TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }
        [Required]
        [Column("Update_User")]
        [StringLength(50)]
        public string UpdateUser { get; set; }
        [Column("Cancel_Date", TypeName = "datetime")]
        public DateTime? CancelDate { get; set; }
        [Column("Cancel_Flag")]
        public bool CancelFlag { get; set; }
        [Required]
        [Column("Cancel_Reason")]
        [StringLength(200)]
        public string CancelReason { get; set; }
        [Required]
        [Column("Cancel_User")]
        [StringLength(50)]
        public string CancelUser { get; set; }
        [Required]
        [Column("Co1_H_1")]
        [StringLength(255)]
        public string Co1H1 { get; set; }
        [Required]
        [Column("Co1_H_2")]
        [StringLength(255)]
        public string Co1H2 { get; set; }
        [Required]
        [Column("Co1_H_3")]
        [StringLength(255)]
        public string Co1H3 { get; set; }
        [Required]
        [Column("Co1_H_4")]
        [StringLength(255)]
        public string Co1H4 { get; set; }
        [Required]
        [Column("Co1_H_5")]
        [StringLength(255)]
        public string Co1H5 { get; set; }
        [Required]
        [Column("Co1_H_6")]
        [StringLength(255)]
        public string Co1H6 { get; set; }
        [Required]
        [Column("Co1_H_7")]
        [StringLength(255)]
        public string Co1H7 { get; set; }
        [Required]
        [Column("Co1_H_8")]
        [StringLength(255)]
        public string Co1H8 { get; set; }
        [Required]
        [Column("Co1_H_9")]
        [StringLength(255)]
        public string Co1H9 { get; set; }
        [Required]
        [Column("Co1_H_10")]
        [StringLength(255)]
        public string Co1H10 { get; set; }
    }
}