// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MQEC_Api.Models
{
    [Table("comCurrency")]
    public partial class ComCurrency
    {
        [Key]
        [Column("CurrencyID")]
        [StringLength(10)]
        public string CurrencyId { get; set; }
        [Required]
        [Column("Currency_Name")]
        [StringLength(20)]
        public string CurrencyName { get; set; }
        [Required]
        [Column("Currency_EngName")]
        [StringLength(50)]
        public string CurrencyEngName { get; set; }
        [Column("Exchange_Rate", TypeName = "decimal(10, 2)")]
        public decimal ExchangeRate { get; set; }
    }
}