// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MQEC_Api.Models
{
    [Table("comDepartment")]
    public partial class ComDepartment
    {
        [Key]
        [Column("Dept_No")]
        [StringLength(10)]
        public string DeptNo { get; set; }
        [Required]
        [Column("Dept_Name")]
        [StringLength(255)]
        public string DeptName { get; set; }
        [Required]
        [Column("Dept_Manager")]
        [StringLength(20)]
        public string DeptManager { get; set; }
        [Column("Dept_Father")]
        [StringLength(10)]
        public string DeptFather { get; set; }
    }
}