// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MQEC_Api.Models
{
    [Table("comFormType")]
    public partial class ComFormType
    {
        [Key]
        [Column("Form_No")]
        [StringLength(50)]
        public string FormNo { get; set; }
        [Key]
        [Column("Type_No")]
        [StringLength(20)]
        public string TypeNo { get; set; }
        [Required]
        [Column("Type_Name")]
        [StringLength(30)]
        public string TypeName { get; set; }
    }
}