// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MQEC_Api.Models
{
    [Table("comInvoiceType")]
    public partial class ComInvoiceType
    {
        [Key]
        [StringLength(10)]
        public string InvoiceType { get; set; }
        [Required]
        [Column("InvoiceType_Name")]
        [StringLength(100)]
        public string InvoiceTypeName { get; set; }
    }
}