// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MQEC_Api.Models
{
    [Table("companyInfo")]
    public partial class CompanyInfo
    {
        [Key]
        [Column("Company_No")]
        [StringLength(10)]
        public string CompanyNo { get; set; }
        [Required]
        [Column("Company_Name")]
        [StringLength(50)]
        public string CompanyName { get; set; }
        [Required]
        [Column("Company_FullName")]
        [StringLength(100)]
        public string CompanyFullName { get; set; }
        [Required]
        [Column("Company_EngName")]
        [StringLength(100)]
        public string CompanyEngName { get; set; }
        [Required]
        [Column("Company_Address")]
        [StringLength(100)]
        public string CompanyAddress { get; set; }
        [Required]
        [StringLength(30)]
        public string Telephone { get; set; }
        [Required]
        [StringLength(30)]
        public string Fax { get; set; }
        [Required]
        [Column("TaxID")]
        [StringLength(20)]
        public string TaxId { get; set; }
        [Required]
        [StringLength(20)]
        public string Principal { get; set; }
    }
}