// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MQEC_Api.Models
{
    [Table("companyInfoReceipt")]
    public partial class CompanyInfoReceipt
    {
        [Key]
        [Column("Company_No")]
        [StringLength(10)]
        public string CompanyNo { get; set; }
        [Required]
        [Column("Company_Name")]
        [StringLength(50)]
        public string CompanyName { get; set; }
        [Key]
        [Column("Receipt_Name")]
        [StringLength(50)]
        public string ReceiptName { get; set; }
        [Required]
        [Column("Receipt_Address")]
        [StringLength(255)]
        public string ReceiptAddress { get; set; }
        [Required]
        [Column("Contact_Person")]
        [StringLength(50)]
        public string ContactPerson { get; set; }
        [Required]
        [Column("Contact_Telephone")]
        [StringLength(50)]
        public string ContactTelephone { get; set; }
        [Required]
        [Column("Contact_Fax")]
        [StringLength(50)]
        public string ContactFax { get; set; }
        [Required]
        public string Memo { get; set; }
        [Required]
        [Column("Location_No")]
        [StringLength(20)]
        public string LocationNo { get; set; }
    }
}