// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MQEC_Api.Models
{
    [Table("comRank")]
    public partial class ComRank
    {
        [Key]
        [Column("Rank_No")]
        public int RankNo { get; set; }
        [Required]
        [Column("Rank_Name")]
        [StringLength(255)]
        public string RankName { get; set; }
    }
}