// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MQEC_Api.Models
{
    [Table("comTurnkeySetting")]
    public partial class ComTurnkeySetting
    {
        [Key]
        [Column("Company_No")]
        [StringLength(50)]
        public string CompanyNo { get; set; }
        [Required]
        [Column("Root_Dir")]
        [StringLength(500)]
        public string RootDir { get; set; }
        [StringLength(150)]
        public string A0101 { get; set; }
        [StringLength(150)]
        public string A0102 { get; set; }
        [StringLength(150)]
        public string A0201 { get; set; }
        [StringLength(150)]
        public string A0202 { get; set; }
        [StringLength(150)]
        public string A0301 { get; set; }
        [StringLength(150)]
        public string A0302 { get; set; }
        [StringLength(150)]
        public string A0401 { get; set; }
        [StringLength(150)]
        public string A0501 { get; set; }
        [StringLength(150)]
        public string A0601 { get; set; }
        [StringLength(150)]
        public string B0101 { get; set; }
        [StringLength(150)]
        public string B0102 { get; set; }
        [StringLength(150)]
        public string B0201 { get; set; }
        [StringLength(150)]
        public string B0202 { get; set; }
        [StringLength(150)]
        public string B0401 { get; set; }
        [StringLength(150)]
        public string B0501 { get; set; }
        [StringLength(150)]
        public string C0401 { get; set; }
        [StringLength(150)]
        public string C0501 { get; set; }
        [StringLength(150)]
        public string C0701 { get; set; }
        [StringLength(150)]
        public string D0401 { get; set; }
        [StringLength(150)]
        public string D0501 { get; set; }
        [StringLength(150)]
        public string E0401 { get; set; }
        [StringLength(150)]
        public string E0402 { get; set; }
        [StringLength(150)]
        public string ProcessResult { get; set; }
        [StringLength(150)]
        public string SummaryResult { get; set; }
    }
}