// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MQEC_Api.Models
{
    public partial class DiscountsUploadStatus
    {
        [Key]
        [Column("Company_No")]
        [StringLength(10)]
        public string CompanyNo { get; set; }
        [Key]
        [Column("TaxID")]
        [StringLength(20)]
        public string TaxId { get; set; }
        [Key]
        [StringLength(5)]
        public string InvoiceCategory { get; set; }
        [Key]
        [StringLength(1)]
        public string InvoiceKind { get; set; }
        [Key]
        [Column("Dis_No")]
        [StringLength(10)]
        public string DisNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? B0401 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? B0501 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? D0401 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? D0501 { get; set; }
    }
}