// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MQEC_Api.Models
{
    [Table("fm")]
    public partial class Fm
    {
        [Key]
        [Column("User_Id")]
        [StringLength(30)]
        public string UserId { get; set; }
        [Required]
        [Column("User_Name")]
        [StringLength(50)]
        public string UserName { get; set; }
        [Required]
        [Column("User_EngName")]
        [StringLength(30)]
        public string UserEngName { get; set; }
        [Required]
        [Column("EncryptPW")]
        public string EncryptPw { get; set; }
        [Required]
        [Column("User_Email")]
        [StringLength(100)]
        public string UserEmail { get; set; }
        [Required]
        [Column("User_Class")]
        [StringLength(4)]
        public string UserClass { get; set; }
        [Required]
        [Column("Signing_Class")]
        [StringLength(20)]
        public string SigningClass { get; set; }
        [Required]
        [Column("Dept_No")]
        [StringLength(10)]
        public string DeptNo { get; set; }
        [Column("Report_Display")]
        public bool ReportDisplay { get; set; }
        public bool Discontinue { get; set; }
        [Column("Signature_Image", TypeName = "image")]
        public byte[] SignatureImage { get; set; }
        [Column("Last_LoginTime", TypeName = "datetime")]
        public DateTime? LastLoginTime { get; set; }
        [Required]
        [Column("System_Language")]
        [StringLength(5)]
        public string SystemLanguage { get; set; }
        [Column("Rank_No")]
        public int RankNo { get; set; }
        [Required]
        [Column("Use_Category")]
        [StringLength(50)]
        public string UseCategory { get; set; }
    }
}