// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MQEC_Api.Models
{
    public partial class InvoiceUploadStatus
    {
        [Key]
        [Column("Company_No")]
        [StringLength(50)]
        public string CompanyNo { get; set; }
        [Key]
        [Column("TaxID")]
        [StringLength(20)]
        public string TaxId { get; set; }
        [Key]
        [StringLength(2)]
        public string InvoiceType { get; set; }
        [Key]
        [StringLength(5)]
        public string InvoiceCategory { get; set; }
        [Key]
        [StringLength(1)]
        public string InvoiceKind { get; set; }
        [Key]
        [StringLength(10)]
        public string InvoiceNumber { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? A0101 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? A0102 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? A0201 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? A0202 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? A0301 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? A0302 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? A0401 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? A0501 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? A0601 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? C0401 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? C0501 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? C0701 { get; set; }
    }
}