// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MQEC_Api.Models
{
    public partial class InvoiceNumberDetails
    {
        [Key]
        [Column("Company_No")]
        [StringLength(50)]
        public string CompanyNo { get; set; }
        [Key]
        [Column("TaxID")]
        [StringLength(20)]
        public string TaxId { get; set; }
        [Required]
        [Column("BranchTaxID")]
        [StringLength(20)]
        public string BranchTaxId { get; set; }
        [Key]
        [StringLength(2)]
        public string InvoiceType { get; set; }
        [Required]
        [StringLength(20)]
        public string InvoiceFunction { get; set; }
        [Key]
        [StringLength(4)]
        public string InvoiceYear { get; set; }
        [Key]
        [Column("InvoiceMonth_From")]
        [StringLength(2)]
        public string InvoiceMonthFrom { get; set; }
        [Key]
        [Column("InvoiceMonth_To")]
        [StringLength(2)]
        public string InvoiceMonthTo { get; set; }
        [Key]
        [Column("Inv_No")]
        [StringLength(20)]
        public string InvNo { get; set; }
        [Key]
        public int Serno { get; set; }
        [Required]
        [StringLength(2)]
        public string InvoiceTrack { get; set; }
        public int Booklet { get; set; }
        [Required]
        [Column("InvoiceNumber_From")]
        [StringLength(8)]
        public string InvoiceNumberFrom { get; set; }
        [Required]
        [Column("InvoiceNumber_To")]
        [StringLength(8)]
        public string InvoiceNumberTo { get; set; }
        [Required]
        [Column("InvoiceNumber_Last")]
        [StringLength(8)]
        public string InvoiceNumberLast { get; set; }
        public int AvaQty { get; set; }
        [Required]
        public string Memo { get; set; }
        [Column("E0401_Date", TypeName = "datetime")]
        public DateTime? E0401Date { get; set; }
        [Column("E0402_Date", TypeName = "datetime")]
        public DateTime? E0402Date { get; set; }
        public bool Discontinued { get; set; }
    }
}