// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MQEC_Api.Models
{
    public partial class Programs
    {
        [Key]
        [Column("Frm_Id")]
        public int FrmId { get; set; }
        [Required]
        [Column("Frm_Cid")]
        [StringLength(100)]
        public string FrmCid { get; set; }
        [Required]
        [Column("Frm_Cname")]
        [StringLength(100)]
        public string FrmCname { get; set; }
        [Required]
        [Column("Frm_Path")]
        [StringLength(100)]
        public string FrmPath { get; set; }
        [Column("Frm_Father_id")]
        public int FrmFatherId { get; set; }
        [Required]
        [Column("Frm_State")]
        [StringLength(20)]
        public string FrmState { get; set; }
        [Required]
        [Column("Frm_Type")]
        [StringLength(10)]
        public string FrmType { get; set; }
        [Column("Frm_Run")]
        public bool? FrmRun { get; set; }
        [Column("Frm_Add")]
        public bool? FrmAdd { get; set; }
        [Column("Frm_Edit")]
        public bool? FrmEdit { get; set; }
        [Column("Frm_Del")]
        public bool? FrmDel { get; set; }
        [Column("Frm_Rept")]
        public bool? FrmRept { get; set; }
        [Column("Frm_Load")]
        public bool? FrmLoad { get; set; }
        [Column("Frm_Load2")]
        public bool? FrmLoad2 { get; set; }
        [Column("Frm_Change")]
        public bool? FrmChange { get; set; }
        [Column("Frm_Change2")]
        public bool? FrmChange2 { get; set; }
        [Column("Frm_Change3")]
        public bool? FrmChange3 { get; set; }
        [Column("Frm_Excel")]
        public bool? FrmExcel { get; set; }
        [Column("Frm_Word")]
        public bool? FrmWord { get; set; }
        [Column("Frm_Approve")]
        public bool? FrmApprove { get; set; }
        [Column("Frm_Mail")]
        public bool? FrmMail { get; set; }
        [Column("Frm_Clone")]
        public bool? FrmClone { get; set; }
    }
}